version: '3'
services:
  app:
    build: ./
    container_name: AuthService
    ports:
      - "8091:8091"
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb_auth
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
